CREATE TYPE ORGANIZATION_TYPE AS ENUM('COMPANY', 'PUBLIC', 'NGO');
CREATE TYPE ORGANIZATION_SIZE AS ENUM('SOLO', 'SMALL', 'MEDIUM', 'ENTERPRISE');
CREATE TYPE ORGANIZATION_STATUS AS ENUM('ACTIVE', 'INACTIVE', 'ARCHIVED');

CREATE TABLE IF NOT EXISTS organizations (
    id          BIGSERIAL PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    type        ORGANIZATION_TYPE,
    size        ORGANIZATION_SIZE,
    website     VARCHAR(255),
    status      ORGANIZATION_STATUS,

    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);